# Generated by Django 4.2.1 on 2023-08-01 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Birga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dollar', models.FloatField()),
                ('ebro', models.FloatField()),
                ('tenge', models.FloatField()),
                ('time', models.DateTimeField()),
            ],
        ),
    ]
