# Generated by Django 4.2.1 on 2023-08-03 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='birga',
            old_name='ebro',
            new_name='eBro',
        ),
        migrations.AddField(
            model_name='birga',
            name='som',
            field=models.FloatField(default=2.1),
            preserve_default=False,
        ),
    ]
